### ISSUE TITLE
Inconsistant AES Decryption in client_server.py

### ISSUE THREAD

**Issue by sfbaker7** [sfbaker7/lightweight_tor#18]
Fernet decryption invalid, likely because the AES token is truncated when passed through the socket. On certain systems, the buffer size is too small to handle token.

If final token is able to decrypt our token into the http response, it only works on an inconsistent basis

**Comment by snggeng** [comment]
Possible cause is that the payloads are getting truncated arbitrarily when they get sent as buffers across the network. 

A workaround could be to attach the length of the buffer at the start of the buffer to ensure that we can `socket.recv` sufficiently for all the buffers to be read.

**Comment by snggeng** [comment]
A fix for this bug was pushed in 55613d8c0101f4b03ccfcbb792aa46cfe5831c1a and 2158159f04be0fc8bba575cd41a1b45e1396b79c. Verified to work on Ubuntu 18.04 and macOS X as of April 21 2019, 17:26pm.
